
// Helper to formatted cookies to Netscape HTTP Cookie File format
export const getYouTubeCookies = async (): Promise<string> => {
    if (!chrome.cookies) {
        console.warn('Chrome Cookies API not available');
        return '';
    }

    try {
        const cookies = await chrome.cookies.getAll({ domain: 'youtube.com' });

        // Format: domain flag path secure expiration name value
        const header = '# Netscape HTTP Cookie File\n# This file is generated by YouTube Downloader Extension\n\n';

        const cookieString = cookies.map((c: chrome.cookies.Cookie) => {
            const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
            const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
            const path = c.path;
            const secure = c.secure ? 'TRUE' : 'FALSE';
            const expiration = c.expirationDate ? Math.floor(c.expirationDate) : 0;
            const name = c.name;
            const value = c.value;

            return `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}`;
        }).join('\n');

        return header + cookieString;
    } catch (error) {
        console.error('Failed to fetch cookies:', error);
        return '';
    }
};

export const getActiveTabUrl = async (): Promise<string | null> => {
    try {
        const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
        return tab?.url || null;
    } catch (e) {
        console.error(e);
        return null;
    }
}
